// AUTHENTICATION ACTIONS
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// ORDER ACTIONS
export const ORDER_START = "ORDER_START";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";
export const GET_ORDER_TOTAL = "GET_ORDER_TOTAL";

// PRODUCT ACTIONS
export const PRODUCT_START = "PRODUCT_START";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";
export const OFF_PRODUCT_SUCCESS = "OFF_PRODUCT_SUCCESS";
export const FEATURED_PRODUCT_SUCCESS = "FEATURED_PRODUCT_SUCCESS";
export const FEATURED_PRODUCT_COUNT = "FEATURED_PRODUCT_COUNT";
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";
export const SET_TO_FEATURED_SUCCESS = "SET_TO_FEATURED_SUCCESS";
export const SET_PRODUCT_QUANTITY = "SET_PRODUCT_QUANTITY";
export const PRODUCT_SEARCH_RESULTS_SUCCESS = "PRODUCT_SEARCH_RESULTS_SUCCESS";
export const PRODUCT_CATEGORIES_SUCCESS = "PRODUCT_CATEGORIES_SUCCESS";

// CHECKOUT ACTIONS
export const CHECKOUT_START = "CHECKOUT_START";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const CHECKOUT_FAIL = "CHECKOUT_FAIL";

// CART ACTIONS
export const CART_START = "CART_START";
export const CART_SUCCESS = "CART_SUCCESS";
export const CART_FAIL = "CART_FAIL";

// BLOG ACTIONS
export const POST_START = "POST_START";
export const POST_SUCCESS = "POST_SUCCESS";
export const SINGLE_POST_SUCCESS = "SINGLE_POST_SUCCESS";
export const POST_CATEGORIES_SUCCESS = "POST_CATEGORIES_SUCCESS";
export const POST_SEARCH_RESULTS_SUCCESS = "SEARCH_RESULTS_SUCCESS";
export const RECENT_POST_SUCCESS = "RECENT_POST_SUCCESS";
export const POST_TAGS_SUCCESS = "POST_TAGS_SUCCESS";
export const POST_FAIL = "POST_FAIL";

// CONTACT ACTION
export const MESSAGE_START = "MESSAGE_START";
export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const MESSAGE_FAIL = "MESSAGE_FAIL";
